### ISSUE TITLE
Automatic Update Fails

### ISSUE THREAD

**Issue by MainMemory** [Lakifume/True-Randomization#17]
After the download finishes, a console window appears with this message:
```
Traceback (most recent call last):
  File "Randomizer.py", line 666, in run
  File "shutil.py", line 749, in rmtree
  File "shutil.py", line 614, in _rmtree_unsafe
  File "shutil.py", line 619, in _rmtree_unsafe
  File "shutil.py", line 617, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'Tools\\UAssetAPI\\Newtonsoft.Json.dll'
```
Afterwards I can complete the update by closing the program and extracting the downloaded zip file myself.

**Comment by Lakifume** [comment]
Ah I see the issue, the fix won't affect the next auto update process but will affect the ones after.
